// Code generated by "go test -run ^TestDoc$ -update"; DO NOT EDIT.
// Edit the command definitions in main.go and run "go generate".

// Vw2026 sends tool calls, one at a time, to the bridge that the cli plug-in
// runs inside Vectorworks 2026.
//
// It is a primitive: each run does exactly what it is told once. It does not
// tell sessions apart, take exclusive use of Vectorworks, lock across
// sessions, retry, or interpret the tools; the caller does those
// (docs/design.md). The bridge and vw2026 exchange files in a spool by the
// protocol in docs/protocol.md.
//
// Each command prints one line of JSON to the standard output, writes the
// reason for a failure to the standard error, and reports the outcome in its
// exit status. Flags may come before or after the positional arguments.
//
//	vw2026 status
//	vw2026 call tools
//	vw2026 launch && vw2026 wait
//
// To update the plug-in, the caller combines the commands (install is not
// implemented yet; see docs/plugin/install-and-update.md):
//
//	vw2026 call quit && vw2026 wait --down && vw2026 install && vw2026 launch && vw2026 wait
//
// The commands exit with
//
//	0  success
//	1  the tool reported a failure (reason on the standard error; with --raw also on the standard output)
//	2  wrong usage
//	3  the bridge is not running
//	4  timed out (call withdrew its request; Vectorworks is running)
//	5  unused (meant "protocol mismatch" up to protocol 2; the numbers are not reused)
//	6  any other failure (cannot write, cannot start, cannot locate the spool)
//	7  Vectorworks is running, so install or uninstall did nothing (planned)
//
// Vectorworks can be running, holding the lock, while the plug-in defers the
// requests, for example during a modal dialog or while undo is being recorded
// (docs/protocol.md). Status does not tell this state apart; call and "wait
// --down" wait up to --timeout and then exit with 4. Recover from 3 and 4
// differently: 3 means Vectorworks is not running, while 4 means it is running
// but did not answer in time, so launching it again or reinstalling the plug-in
// does not help.
//
// Usage:
//
//	vw2026 <command> [flags]
//
// The commands are:
//
//	status     Report whether the bridge is running
//	call       Call one tool
//	wait       Wait until the bridge starts or stops
//	launch     Start Vectorworks
//	version    Print the versions of the CLI and the protocol
//
// Use "vw2026 <command> --help" or "vw2026 help <command>" for more information about a command.
//
// # Report whether the bridge is running
//
// Usage:
//
//	vw2026 status [flags]
//
// Status reports whether the bridge is running. The answer depends only on
// whether the plug-in holds the lock file (bridge.lock) in the spool; see
// docs/protocol.md. Status does not tell a busy Vectorworks from a responsive
// one. Use "vw2026 call ping" for the version of the plug-in.
//
// It prints one of
//
//	{"running":true,"spool":"..."}
//	{"running":false,"spool":"...","reason":"..."}
//
// and exits with 3 when the bridge is not running.
//
// Arguments and flags:
//
//	--spool=DIR              Spool directory. The default is <CLI>/spool; another one is for tests, as the plug-in never reads it. ($VW2026_SPOOL)
//
// # Call one tool
//
// Usage:
//
//	vw2026 call <tool> [<args>] [flags]
//
// Call calls one tool of the bridge and prints its result. "vw2026 call tools"
// lists the tools; docs/plugin/tools.md describes them.
//
// The arguments are a JSON object. "-" reads them from the standard input.
// Without them, the tool is called with no arguments. Call does not check the
// arguments against the tool; the plug-in does.
//
//	vw2026 call layers '{"include_sheets":false}'
//	echo '{"layer":"1F"}' | vw2026 call layer_objects -
//
// On success, call prints the result of the tool. With --raw it prints the
// whole response. When the tool fails, call writes the reason to the standard
// error and exits with 1. When --timeout runs out, call withdraws the request
// and exits with 4.
//
// Arguments and flags:
//
//	<tool>                   Tool to call ("vw2026 call tools" lists them).
//	[<args>]                 Arguments as a JSON object, or - to read them from the standard input.
//	--spool=DIR              Spool directory. The default is <CLI>/spool; another one is for tests, as the plug-in never reads it. ($VW2026_SPOOL)
//	--raw                    Print the whole response (ok, result, and error).
//	--timeout=SECONDS        How long to wait for the response (default 30).
//
// # Wait until the bridge starts or stops
//
// Usage:
//
//	vw2026 wait [flags]
//
// Wait waits until the bridge starts, that is, until the plug-in takes the lock.
// With --down it waits until the bridge stops (the lock is released). It prints
// the same output as status, or exits with 4 when --timeout runs out.
//
// Vectorworks keeps the lock while it shows the dialog that asks to save the
// drawings, so "wait --down" does not take that dialog for a stop.
//
// Arguments and flags:
//
//	--spool=DIR              Spool directory. The default is <CLI>/spool; another one is for tests, as the plug-in never reads it. ($VW2026_SPOOL)
//	--down                   Wait until the bridge stops instead.
//	--timeout=SECONDS        How long to wait (default 120).
//
// # Start Vectorworks
//
// Usage:
//
//	vw2026 launch [flags]
//
// Launch starts Vectorworks unless the bridge is already running. It does not
// wait for the bridge; run "vw2026 wait" next to wait for it.
//
//	vw2026 launch && vw2026 wait
//
// It prints one of
//
//	{"launched":true,"command":[...]}
//	{"running":true,"spool":"...","launched":false}
//
// The default application is "Vectorworks 2026" on macOS, started with
// "open -a", and %ProgramFiles%\Vectorworks 2026\Vectorworks2026.exe on
// Windows. Launch does not search other places; name them with --app. A value
// that does not end in .app is started as an executable.
//
// When Vectorworks is running but the bridge is not (the plug-in is not
// installed), launch exits with 3.
//
// Arguments and flags:
//
//	--spool=DIR              Spool directory. The default is <CLI>/spool; another one is for tests, as the plug-in never reads it. ($VW2026_SPOOL)
//	--app=NAME-OR-PATH       Application or executable to start. ($VW2026_APP)
//
// # Print the versions of the CLI and the protocol
//
// Usage:
//
//	vw2026 version [flags]
//
// Version prints the version of this CLI and the version of the protocol it
// speaks (docs/protocol.md).
//
//	{"version":"abc1234","protocol":3}
//
// Arguments and flags:
//
//	--spool=DIR              Spool directory. The default is <CLI>/spool; another one is for tests, as the plug-in never reads it. ($VW2026_SPOOL)
//
// # Building and testing
//
// In the cli module:
//
//	go vet ./...
//	go test ./...
//	go build -ldflags "-X main.version=$(git describe --always)" -o vw2026 ./cmd/vw2026
//
// The tests exchange requests with a fake plug-in (cli/internal/fakeplugin), a
// goroutine that holds the lock and writes responses to the spool.
//
// This documentation is generated from the command definitions in main.go
// (their tags and Help methods). After changing them, regenerate it:
//
//	go generate ./cmd/vw2026
package main
