// Code generated by "go test -run ^TestDoc$ -update"; DO NOT EDIT.
// Edit the command definitions in cmd/vw2026 and run "go generate".

// Vw2026 sends tool calls, one at a time, to the bridge that the cli plug-in
// runs inside Vectorworks 2026.
//
// It is a primitive: each run does exactly what it is told once. It does not
// tell sessions apart, take exclusive use of Vectorworks, lock across
// sessions, retry, or interpret the tools; the caller does those
// (docs/design.md). The bridge and vw2026 exchange files in a spool by the
// protocol in docs/protocol.md.
//
// Each command prints one line of JSON to the standard output, writes the
// reason for a failure to the standard error, and reports the outcome in its
// exit status (see "vw2026 help exit-status"). Flags may come before or after
// the positional arguments.
//
// To update the plug-in, the caller combines the commands (install is not
// implemented yet; see docs/plugin/install-and-update.md):
//
//	vw2026 call quit && vw2026 wait --down && vw2026 install && vw2026 launch && vw2026 wait
//
// Usage:
//
//	vw2026 <command> [arguments]
//
// The commands are:
//
//	status       report whether the bridge is running
//	call         call one tool
//	wait         wait until the bridge starts or stops
//	launch       start Vectorworks
//	version      print the versions of the CLI and the protocol
//
// Use "vw2026 help <command>" for more information about a command.
//
// Additional help topics:
//
//	spool        where the spool is
//	exit-status  exit status of the commands
//	build        building and testing vw2026
//
// Use "vw2026 help <topic>" for more information about that topic.
//
// # Report whether the bridge is running
//
// Usage:
//
//	vw2026 status [--spool <dir>]
//
// Status reports whether the bridge is running. The answer depends only on
// whether the plug-in holds the lock file (bridge.lock) in the spool; see
// docs/protocol.md. Status does not tell a busy Vectorworks from a responsive
// one (see "vw2026 help exit-status"). Use "vw2026 call ping" for the version
// of the plug-in.
//
// It prints one of
//
//	{"running":true,"spool":"..."}
//	{"running":false,"spool":"...","reason":"..."}
//
// and exits with 3 when the bridge is not running.
//
// The --spool flag selects the spool; see "vw2026 help spool".
//
// # Call one tool
//
// Usage:
//
//	vw2026 call <tool> [args-json | -] [--raw] [--timeout <seconds>] [--spool <dir>]
//
// Call calls one tool of the bridge and prints its result. "vw2026 call tools"
// lists the tools; docs/plugin/tools.md describes them.
//
// The arguments are a JSON object. "-" reads them from the standard input.
// Without them, the tool is called with no arguments. Call does not check the
// arguments against the tool; the plug-in does.
//
//	vw2026 call layers '{"include_sheets":false}'
//	echo '{"layer":"1F"}' | vw2026 call layer_objects -
//
// On success, call prints the result of the tool. With --raw it prints the
// whole response (ok, result, and error). When the tool fails, call writes the
// reason to the standard error and exits with 1.
//
// The --timeout flag (default 30 seconds) limits the wait for the response.
// When it runs out, call withdraws the request and exits with 4.
//
// # Wait until the bridge starts or stops
//
// Usage:
//
//	vw2026 wait [--down] [--timeout <seconds>] [--spool <dir>]
//
// Wait waits until the bridge starts, that is, until the plug-in takes the lock.
// With --down it waits until the bridge stops (the lock is released). It prints
// the same output as status.
//
// The --timeout flag (default 120 seconds) limits the wait. When it runs out,
// wait exits with 4.
//
// Vectorworks keeps the lock while it shows the dialog that asks to save the
// drawings, so "wait --down" does not take that dialog for a stop.
//
// # Start Vectorworks
//
// Usage:
//
//	vw2026 launch [--app <name-or-path>] [--spool <dir>]
//
// Launch starts Vectorworks unless the bridge is already running. It does not
// wait for the bridge; run "vw2026 wait" next to wait for it.
//
//	vw2026 launch && vw2026 wait
//
// It prints one of
//
//	{"launched":true,"command":[...]}
//	{"running":true,"spool":"...","launched":false}
//
// The --app flag (or VW2026_APP) names the application. The default is
// "Vectorworks 2026" on macOS, started with "open -a", and
// %ProgramFiles%\Vectorworks 2026\Vectorworks2026.exe on Windows. Launch does
// not search other places; name them with --app. A value that does not end in
// .app is started as an executable.
//
// When Vectorworks is running but the bridge is not (the plug-in is not
// installed), launch exits with 3.
//
// # Print the versions of the CLI and the protocol
//
// Usage:
//
//	vw2026 version
//
// Version prints the version of this CLI and the version of the protocol it
// speaks (docs/protocol.md).
//
//	{"version":"abc1234","protocol":3}
//
// # Where the spool is
//
// The spool is the directory through which vw2026 and the bridge exchange
// requests and responses. Its default is <CLI>/spool, where <CLI> is the
// directory of the CLI (docs/protocol.md). The plug-in uses the same rule, so
// both find the same place without searching.
//
// The --spool flag, or the VW2026_SPOOL environment variable, points vw2026 at
// another directory. That is for tests: the plug-in never reads it, so with a
// production Vectorworks the bridge is then reported as not running.
//
// # Exit status of the commands
//
// The commands exit with
//
//	0  success
//	1  the tool reported a failure (reason on the standard error; with --raw also on the standard output)
//	2  wrong usage
//	3  the bridge is not running
//	4  timed out (call withdrew its request; Vectorworks is running)
//	5  unused (meant "protocol mismatch" up to protocol 2; the numbers are not reused)
//	6  any other failure (cannot write, cannot start, cannot locate the spool)
//	7  Vectorworks is running, so install or uninstall did nothing (planned)
//
// Vectorworks can be running, holding the lock, while the plug-in defers the
// requests, for example during a modal dialog or while undo is being recorded
// (docs/protocol.md). Status does not tell this state apart. Call and "wait
// --down" wait up to --timeout and then exit with 4.
//
// Recover from 3 and 4 differently: 3 means Vectorworks is not running; 4 means
// it is running but did not answer in time, so launching it again or
// reinstalling the plug-in does not help.
//
// # Building and testing vw2026
//
// In the cli module:
//
//	go vet ./...
//	go test ./...
//	go build -ldflags "-X main.version=$(git describe --always)" -o vw2026 ./cmd/vw2026
//
// The tests exchange requests with a fake plug-in (cli/internal/fakeplugin), a
// goroutine that holds the lock and writes responses to the spool.
//
// The command definitions in cmd/vw2026 are the source of this documentation.
// After changing them, regenerate doc.go:
//
//	go generate ./cmd/vw2026
package main
