package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/alecthomas/kong"
)

//go:generate go test -run ^TestDoc$ -update

// buildDoc is the part of doc.go that is not about using a command, so it has
// no place in the help output.
const buildDoc = `
In the cli module:

	go vet ./...
	go test ./...
	go build -ldflags "-X main.version=$(git describe --always)" -o vw2026 ./cmd/vw2026

The tests exchange requests with a fake plug-in (cli/internal/fakeplugin), a
goroutine that holds the lock and writes responses to the spool.

This documentation is generated from the command definitions in main.go
(their tags and Help methods). After changing them, regenerate it:

	go generate ./cmd/vw2026
`

// renderDoc returns the contents of doc.go, built from the same kong model as
// the help output so that the two cannot disagree.
func renderDoc() ([]byte, error) {
	var grammar cli
	parser, err := newParser(&grammar, env{})
	if err != nil {
		return nil, err
	}
	app := parser.Model

	var text strings.Builder
	text.WriteString(trim(app.Detail) + "\n\nUsage:\n\n\tvw2026 <command> [flags]\n\nThe commands are:\n\n")
	commands := app.Leaves(true)
	for _, cmd := range commands {
		fmt.Fprintf(&text, "\t%-10s %s\n", cmd.Name, strings.TrimSuffix(cmd.Help, "."))
	}
	text.WriteString("\nUse \"vw2026 <command> --help\" or \"vw2026 help <command>\" for more information about a command.\n")
	for _, cmd := range commands {
		fmt.Fprintf(&text, "\n# %s\n\nUsage:\n\n\tvw2026 %s\n\n%s\n", strings.TrimSuffix(cmd.Help, "."), cmd.Summary(), trim(cmd.Detail))
		writeValues(&text, cmd)
	}
	fmt.Fprintf(&text, "\n# Building and testing\n\n%s\n", trim(buildDoc))

	var src bytes.Buffer
	src.WriteString("// Code generated by \"go test -run ^TestDoc$ -update\"; DO NOT EDIT.\n")
	src.WriteString("// Edit the command definitions in main.go and run \"go generate\".\n\n")
	for _, line := range strings.Split(strings.TrimRight(text.String(), "\n"), "\n") {
		switch {
		case line == "":
			src.WriteString("//\n")
		case strings.HasPrefix(line, "\t"):
			src.WriteString("//" + line + "\n")
		default:
			src.WriteString("// " + line + "\n")
		}
	}
	src.WriteString("package main\n")
	// gofmt reformats doc comments; formatting here keeps doc.go stable under it.
	return format.Source(src.Bytes())
}

// writeValues lists the arguments and flags of cmd as a code block.
func writeValues(text *strings.Builder, cmd *kong.Node) {
	var rows [][2]string
	for _, arg := range cmd.Positional {
		rows = append(rows, [2]string{arg.Summary(), arg.Help})
	}
	for _, group := range cmd.AllFlags(true) {
		for _, flag := range group {
			if flag.Name == "help" {
				continue
			}
			help := flag.Help
			for _, name := range flag.Envs {
				help += fmt.Sprintf(" ($%s)", name)
			}
			rows = append(rows, [2]string{flag.Summary(), help})
		}
	}
	if len(rows) == 0 {
		return
	}
	text.WriteString("\nArguments and flags:\n\n")
	for _, row := range rows {
		fmt.Fprintf(text, "\t%-24s %s\n", row[0], row[1])
	}
}

func trim(s string) string { return strings.Trim(s, "\n") }
